version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    #port container/ port pc
    - "3307:3306"
    volumes:
      - jhonatan_data:/var/lib/mysql
volumes:
  jhonatan_data:
